export const MuseumList = [
  "Biblioteca Patrimonial Recoleta Dominica",
  "Casa Colorada",
  "Casa Museo Eduardo Frei Montalva",
  "Centro Nacional de Arte Contemporáneo Cerrillos",
  "Enoteca del cerro San Cristóbal",
  "La Chascona",
  "Museo a Cielo Abierto en San Miguel",
  "Museo Artequin",
  "Museo Arqueológico",
  "Museo Arte Popular Americano",
  "Museo de Anatomía",
  "Museo de Artes Decorativas",
  "Museo de Artes Visuales",
  "Museo de Bomberos",
  "Museo de Cera de Las Condes",
  "Museo de Ciencia y Tecnología",
  "Museo de Colo-Colo",
  "Museo de la Educación Gabriela Mistral",
  "Museo de la Guerra del Pacífico",
  "Museo de la Historieta",
  "Museo de la Memoria y los Derechos Humanos",
  "Museo de la Moda",
  "Museo de la Solidaridad Salvador Allende",
  "Museo de la Vivienda Tradicional Local",
  "Museo de Química y Farmacia Profesor César Leyton Caravagno",
  "Museo del Ahorro",
  "Museo del Carmen de Maipú",
  "Museo del Sonido",
  "Museo Ferroviario",
  "Museo Histórico Carabineros",
  "Museo Histórico Dominico",
  "Museo Histórico Nacional",
  "Museo Histórico y Militar",
  "Museo Infantil",
  "Museo Interactivo Las Condes",
  "Museo Interactivo Mirador",
  "Museo Jedimar",
  "Museo Judío Alemán",
  "Museo La Merced",
  "Museo Nacional Aeronáutico y del Espacio",
  "Museo Nacional Benjamín Vicuña Mackenna",
  "Museo Nacional de Historia Natural",
  "Museo Nacional de Medicina Dr. Enrique Laval",
  "Museo Numismático del Banco Central",
  "Museo Ocean Pacific's",
  "Museo Parque de las Esculturas de Providencia",
  "Museo Postal y Telegráfico",
  "Museo Ralli",
  "Museo San Francisco",
  "Museo Violeta Parra",
  "Museo Chileno de Arte Precolombino",
  "Nido 20",
  "Nuevo Museo",
  "Parque del Cómic de San Miguel",
  "Paseo de las Esculturas La Pastora",
  "Santuario del Padre Hurtado",
];
